### PR TITLE
Chef cookbooks fixing derived attributes

### PR DESCRIPTION
**Pull request by iennae**

### CODE REVIEW

**Comment by scalp42** [comment]
@iennae it looks like a regression to me, you're moving from attributes to hardcoded versions.

What's the issue you're running into ?

If it's related to a wrapper cookbook where you're changing the version for example, make sure to specify any default attribute that interpolates the version :smile:

**Comment by iennae** [comment]
@scalp42 the problem is folks are filing issues about derived attributes. I updated the documentation so that folks can explicitly set the correct attributes as derived isn't working correctly.

**Comment by iennae** [comment]
after talking to Tim, going to do something different here.

**Comment by scalp42** [comment]
I opened a PR which might help.

**Pull request closed without merging**
